### ISSUE TITLE
JSX files ignored

### ISSUE THREAD

**Issue by tomitrescak** [insin/nwb#162]
First, let me thank you for this fantastic project! I've been struggling with create-react-app a bit as they took the approach all or nothing which you leave space for nice configuration.

My problem is that I'm trying to make this work with Typescript. I prefer to compile files first to Javascript and then load them using your tool.

The problem is that typescript compiles file into JSX which is ignored.
I tried following config but it did not work:

```
module.exports = {
  webpack: {
    extra: {
      resolve: {
         extensions:  ['.js', '.jsx'],
      }
    }
  }
}
```

**Comment by tomitrescak** [comment]
Here is the answer:

```js
module.exports = {
  babel: {
    plugins: ['jsx-control-statements']
  },
  webpack: {
    loaders: {
      babel: {
        test: /\.jsx?/
      }
    },
    extra: {
      resolve: {
        extensions: ['', '.js', '.jsx', '.json']
      },
      node: {
        process: false
      }
    }
  }
}
```

**Comment by jstralko** [comment]
Hello Tom, 

I'm trying to get webpack to resolve jsx when building the bundle file but getting the following erorr when running:

`nwb serve --reload`
`Module build failed: ReferenceError: Unknown plugin "jsx-control-statements" specified in "base" at 3, attempted to resolve relative to "/Volumes/Source/TheOutlaws/ui/neo/src"
    at /Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-loader/index.js:14:22)
    at /Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-loader/lib/fs-cache.js:145:18
    at ReadFileContext.callback (/Volumes/Source/TheOutlaws/ui/neo/node_modules/nwb/node_modules/babel-loader/lib/fs-cache.js:28:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
 @ multi main`

Am I missing a dependency or doing something wrong.  Here is my full nwb.config.js file:

`cat nwb.config.js
module.exports = {
  type: 'react-app',
  babel: {
      plugins: ['jsx-control-statements']
  },
  webpack: {
    loaders: {
      babel: {
        test: /\.jsx?/
      }
    },
    extra: {
      devtool: '#inline-source-map',
      resolve: {
        extensions: ['', '.js', '.jsx']
      },
      node: {
        process: false
      }
    }
  }
}`
