### ISSUE TITLE
inferno build command throws TypeError

### ISSUE THREAD

**Issue by balazs4** [insin/nwb#241]
This issue is a: 

- [X] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

I wanted to use the following **inferno** quick commands for that file:

````javascript
// foobar.js
export default () => (<h1>Hello from inferno</h1>)
````

``inferno run foobar.js`` works as expected. (dependency installation, compilation, serving) :+1: 

but

``inferno build foobar.js``  throws the following error: :-1: 

````
$ inferno build foobar.js                                                                                                                                                                                     

✔ Cleaning app
/home/balazs4/Src/nwb/lib/commands/build-inferno.js:73
    config.resolve.alias['inferno'] = _path2.default.dirname(_resolve2.default.sync('inferno/package.json', { basedir: process.cwd() }));
                  ^
TypeError: Cannot read property 'alias' of undefined
    at buildConfig (/home/balazs4/Src/nwb/lib/commands/build-inferno.js:73:19)
    at webpackBuild (/home/balazs4/Src/nwb/lib/webpackBuild.js:48:19)
    at Array.<anonymous> (/home/balazs4/Src/nwb/lib/commands/build-inferno.js:100:39)
    at each (/home/balazs4/Src/nwb/node_modules/run-series/index.js:17:24)
    at /home/balazs4/Src/nwb/lib/utils.js:71:7
    at end (/home/balazs4/Src/nwb/node_modules/run-series/index.js:8:15)
    at done (/home/balazs4/Src/nwb/node_modules/run-series/index.js:11:10)
    at each (/home/balazs4/Src/nwb/node_modules/run-series/index.js:16:43)
    at next (/home/balazs4/Src/nwb/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/home/balazs4/Src/nwb/node_modules/rimraf/rimraf.js:110:9)
````

The issue can be reproduced on a windows machine as well.

**Comment by insin** [comment]
Fixed in v0.14.3 - thanks!
