### ISSUE TITLE
nwb Test failing to run from karma after upgrade to 0.15.x

### ISSUE THREAD

**Issue by caseybaggz** [insin/nwb#274]
This issue is a: 

- [X] Bug report
- [ ] Feature request
- [ ] Question / support request
- [ ] Other

Just upgraded from 13.3 to 0.15.x and am getting this error when trying to run tests:
```
$ nwb test-react
Error running command: Path must be a string. Received null
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.extname (path.js:1431:5)
    at phantomJSExePath (/Users/casey/github/whiplash-ui-library/node_modules/karma-phantomjs-launcher/index.js:19:12)
    at Object.<anonymous> (/Users/casey/github/whiplash-ui-library/node_modules/karma-phantomjs-launcher/index.js:104:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getKarmaPluginConfig (/Users/casey/github/whiplash-ui-library/node_modules/nwb/lib/createKarmaConfig.js:144:18)
    at createKarmaConfig (/Users/casey/github/whiplash-ui-library/node_modules/nwb/lib/createKarmaConfig.js:164:31)
    at karmaServer (/Users/casey/github/whiplash-ui-library/node_modules/nwb/lib/karmaServer.js:25:53)
    at testReact (/Users/casey/github/whiplash-ui-library/node_modules/nwb/lib/commands/test-react.js:13:29)
    at cli (/Users/casey/github/whiplash-ui-library/node_modules/nwb/lib/cli.js:246:3)
    at Object.<anonymous> (/Users/casey/github/whiplash-ui-library/node_modules/nwb/lib/bin/nwb.js:31:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3
error Command failed with exit code 1.
```

The demo & build commands run fine, it's only the test command.

**Comment by caseybaggz** [comment]
FYI, I went ahead and update our library since the build works fine but Travis is just giving us a failing pill due to this issue. :(

**Comment by insin** [comment]
Try deleting `node_modules` cache config from your `.travis.yml` config.

See https://github.com/insin/nwb/issues/271#issuecomment-281725990

**Comment by caseybaggz** [comment]
@insin unfortunately, it's not a Travis problem as the test's fail to run locally. Additionally, we use yarn vs. npm so we aren't caching the `node_modules` in our `.travis.yml`.

I have cleaned both the yarn and npm cache and it's still failing to run (locally).

**Comment by caseybaggz** [comment]
@insin I went ahead and deleted `node_modules` and re-installed everything, now I'm getting this locally and on Travis:

```
START:
(node:2478) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
<--- Last few GCs --->
[2478:0x2d94ad0]    37785 ms: Mark-sweep 1385.2 (1448.1) -> 1384.7 (1457.6) MB, 133.3 / 0.0 ms  allocation failure GC in old space requested
[2478:0x2d94ad0]    37905 ms: Mark-sweep 1384.7 (1457.6) -> 1384.7 (1458.1) MB, 112.2 / 0.0 ms  allocation failure GC in old space requested
[2478:0x2d94ad0]    38069 ms: Mark-sweep 1384.7 (1458.1) -> 1384.7 (1431.1) MB, 151.9 / 0.0 ms  last resort 
[2478:0x2d94ad0]    38264 ms: Mark-sweep 1384.7 (1431.1) -> 1384.7 (1423.1) MB, 194.7 / 0.0 ms  last resort 
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x2a9f2e226729 <JS Object>
    0: builtin exit frame: parse(this=0x2a9f2e21a859 <a JSON with map 0x2a99053d9>,0x3374bb902201 <Very long string[2632208]>)
    1: sourceMapData [/home/travis/build/whiplashmerch/whiplash-ui-library/node_modules/karma-sourcemap-loader/index.js:12] [pc=0x29e18a12f76](this=0x239521697d61 <JS Global Object>,data=0x3374bb902201 <Very long string[2632208]>)
    2: inlineMap [/home/travis/build/w...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x12b288c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
 7: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
 8: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
 9: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
10: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
11: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
12: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
13: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
14: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
15: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
16: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [node]
17: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<false>::ScanJsonString<false>() [node]
18: v8::internal::JsonParser<false>::ParseJsonValue() [node]
19: v8::internal::JsonParser<false>::ParseJsonArray() [node]
20: v8::internal::JsonParser<false>::ParseJsonValue() [node]
21: v8::internal::JsonParser<false>::ParseJsonObject() [node]
22: v8::internal::JsonParser<false>::ParseJsonValue() [node]
23: v8::internal::JsonParser<false>::ParseJson() [node]
24: v8::internal::Builtin_JsonParse(int, v8::internal::Object**, v8::internal::Isolate*) [node]
25: 0x29e16884167
Aborted (core dumped)
error Command failed with exit code 134.
```

**Comment by caseybaggz** [comment]
You can find the code relevant to this issue in our current `update-travis-yml` branch as well:
https://github.com/whiplashmerch/whiplash-ui-library/tree/update-travis-yml

**Comment by insin** [comment]
I can replicate this locally.

One of the suggestions in [this issue](https://github.com/karma-runner/karma/issues/1868#issuecomment-264462542) was to use `require.context`, which made tests run for me locally:

**tests.webpack.js**
```js
var context = require.context('./tests', true, /\.test\.js$/)
context.keys().forEach(context)
```

**nwb.config.js**
```
module.exports = {
  // ...
  karma: {
    testContext: 'tests.webpack.js'
  }
  // ...
}
```

**Comment by caseybaggz** [comment]
@insin adding in the `test.webpack.js` config worked! Thanks for the help brotha. 👍
