### ISSUE TITLE
Permissions issue installing globally 

### ISSUE THREAD

**Issue by cbartram** [insin/nwb#345]
This issue is a
- Bug report

Is the version of `nwb` you're using installed globally or locally?

Globally

Which versions of Node.js, npm and nwb are you using (if using it globally)?

NodeJS 8.0.0
NPM 5.0.4
nwb cannot be installed

Which modules are installed in your project?
├── babel-eslint@4.1.8
├── classnames@2.2.5
├── eslint@1.10.3
├── eslint-plugin-react@3.16.1
├── gulp@3.9.1
├── jest@20.0.4
├── material-ui@0.18.5
├── prettier@1.5.2
├── UNMET DEPENDENCY prop-types@latest
├── UNMET PEER DEPENDENCY react@0.14.9
├── react-color@2.13.0
├── react-component-gulp-tasks@0.7.7
├── UNMET PEER DEPENDENCY react-dom@0.14.9
├── react-tap-event-plugin@2.0.1
└── react-test-renderer@15.6.1
The error Im getting is a basic permissions error when npm is installing nwb globally it occurs when npm is installing the package PhantomJS

Ive ensured that the file permissions are set to 777 for the node_modules folder and ive even tried running the command 
`sudo npm install -g nwb`

Im using a Macbook Pro with the touch bar if that helps any also I have 3 separate macs and this happens to all of them...

Any help? 

here is the stack trace 
```
Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Found PhantomJS at /usr/local/lib/node_modules/phantomjs/lib/phantom/bin/phantomjs ...verifying
Writing location.js file
Error checking path, continuing { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/location.js'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.writeFileSync (fs.js:1287:33)
    at writeLocationFile (/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/install.js:366:11)
    at nextTickCallback (/usr/local/lib/node_modules/nwb/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/location.js' }
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1499810573739/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1499810573739/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1499810573739/phantomjs-2.1.1-macosx',
  dest: '/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1499810573739/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/nwb/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christianbartram/.npm/_logs/2017-07-11T22_03_10_460Z-debug.log
```

**Comment by andereb081** [comment]
sudo npm install -g nwb --unsafe-perm
Will help someone still facing this

**Comment by briancollins081** [comment]
`sudo npm install -g nwb --unsafe-perm` 
Will help someone still facing this
