### ISSUE TITLE
Using nwb published component in Angular App

### ISSUE THREAD

**Issue by mars76** [insin/nwb#371]
This issue is a: 
- Question / support request

I have created a react-component using nwb and able to publish to my local npm repo.
How ever when i tried to use these Components in an Angular app i am running into Issues.

When i tried to do

import MyCardComponent from 'my-components-react';

The Angular project (my-components-test) complains that there is no "MyCardComponent"

`WARNING in ./src/app/RepCard.ts
11:68-82 "export 'default' (imported as 'MyCardComponent') was not found in 'my-components-react'
    at HarmonyImportSpecifierDependency._getErrors (/Users/git-projects/my-components-test/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (/Users/git-projects/analytics/my-components-test/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/git-projects/my-components-test/node_modules/webpack/lib/Compilation.js:677:24)
    at Compilation.finish (/Users/git-projects/my-components-test/node_modules/webpack/lib/Compilation.js:535:9)
    at applyPluginsParallel.err (/Users/git-projects/my-components-test/node_modules/webpack/lib/Compiler.js:512:17)
    at /Users/git-projects/my-components-test/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/git-projects/my-components-test/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/git-projects/my-components-test/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
`
Could you pls let us know what i am doing wrong.

Thanks

**Comment by jamrizzi** [comment]
https://github.com/insin/nwb/issues/362
