### ISSUE TITLE
Installing nwb failed due to `Failed at the phantomjs-prebuilt@2.1.16 install script`

### ISSUE THREAD

**Issue by ivanasetiawan** [insin/nwb#424]
This issue is a: 

- Question / support request

I ran `npm install -g nwb` but it failed to `Failed at the phantomjs-prebuilt@2.1.16 install script`.
My node -v is `v8.9.1` & npm `5.6.0`

**Comment by insin** [comment]
Does this work?

```npm install -g --unsafe-perm nwb```

**Comment by Carr1005** [comment]
I have encountered a similar issue today, but not sure if @ivanasetiawan has the same one?
In my situation, the output just mentioned that :
`tar (child): bzip2: Cannot exec: No such file or directory`
Cause I'm using a very minimal docker debian base image, so I don't have bzip2 that `tar` need to uncompress .bz2 file for installing phantomjs-prebuilt.
So I just install it and everything goes cool.
`apt-get install bzip2`

Full related error information :
```
root@32f0ad0b58ca:/# npm install -g nwb
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/bin/nwb -> /usr/lib/node_modules/nwb/lib/bin/nwb.js

> uws@0.14.5 install /usr/lib/node_modules/nwb/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> phantomjs-prebuilt@2.1.16 install /usr/lib/node_modules/nwb/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:199:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
/usr/lib
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/nwb/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN babel-plugin-inferno@3.3.1 requires a peer of inferno@3.x but none was installed.
npm ERR! Linux 4.4.27-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "nwb"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
```

**Comment by ivanasetiawan** [comment]
OK after trying many things.. I solved this error by uninstalling yarn.

**Comment by dnfield** [comment]
Any chance you could make Phantom a peer dependency?  I'm behind a proxy at work and cannot install PhantomJS.

**Comment by jbadeau** [comment]
Please make phantom a peer dependency.
