### ISSUE TITLE
Can't get 'babel-plugin-emotion' to work

### ISSUE THREAD

**Issue by iatzmon** [insin/nwb#447]
This issue is a:
- Question / support request

I'm trying to install and use the emotion babel plugin with nwb and I can't get it to work.
I installed it by running
```
npm install --save babel-plugin-emotion
```

And then adding the following configuration to my nwb.config:
```
{
    ...
    babel: {
        "plugins": ["emotion"]
    }
    ...
}
```

When I run the start script I get the following error:
```
 ERROR  in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "../node_modules/emotion" specified in "base" at 1, attempted to resolve relative to "C:\\Dev\\Deep\\deep-editor\\deep-editor-admin\\src"
    at C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-loader\lib\index.js:50:20)
    at C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-loader\lib\fs-cache.js:118:18
    at ReadFileContext.callback (C:\Dev\Deep\deep-editor\deep-editor-admin\node_modules\babel-loader\lib\fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./node_modules/nwb/polyfills.js (webpack)-dev-server/client?/ (webpack)/hot/only-dev-server.js ./src/index.js
```

Any idea what the problem is?

Thanks

**Comment by iatzmon** [comment]
This issue seems to be specific to my project configuration, I tried to create a new nwb app and managed to configure the plugin without any issues

**Comment by iatzmon** [comment]
Ok, I managed to resolve the issue. The problem happened because I'm using aliases, and was caused by this issue: [https://github.com/babel/babel/issues/3969](url). 
The solution was to require the plugin in the config file and pass it to the babel config instead of passing it by name.

```
{
    ...
    babel: {
        "plugins": [require("babel-plugin-emotion")]
    }
    ...
}
```
