### ISSUE TITLE
Cannot find module 'core-util-is'

### ISSUE THREAD

**Issue by anakinjay** [insin/nwb#78]
Hello,
Just tried installing this and got the following error:

```
Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nwb/node_modules/readable-stream/lib/_stream_duplex.js:25:12)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
```

running 'npm install core-util-is' fixed the issue and allowed me to install, but I don't see anything in the instructions saying you have to manually install this before installing nwb

**Comment by insin** [comment]
Sounds like an npm issue. This module isn't a direct dependency of nwb. Searching for that error message brings up a bunch of the same reports for different projects - nuking `node_modules/` and starting from scratch seems to be the solution if this happens to you. I've not encounters it personally.
