### ISSUE TITLE
Unknown plugin "typecheck"

### ISSUE THREAD

**Issue by maslianok** [insin/nwb#80]
This error appears after when I'm trying to run `nwb serve`
nwb version 0.8.1

```
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "typecheck"
    at PluginManager.subnormaliseString (/usr/local/lib/node_modules/nwb/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/usr/local/lib/node_modules/nwb/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/usr/local/lib/node_modules/nwb/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/usr/local/lib/node_modules/nwb/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/usr/local/lib/node_modules/nwb/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/usr/local/lib/node_modules/nwb/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/usr/local/lib/node_modules/nwb/node_modules/babel-loader/index.js:71:12)
 @ multi main
```

**Comment by insin** [comment]
Do you have a `.babelrc` somewhere in your project's path or your home directory?

**Comment by maslianok** [comment]
@insin No, I don't.

OS X El Capitan
I don't have any global package.

Steps to reproduce:
```
npm install -g nwb // Success
nwb new react-app datalabs // Success
cd datalabs // Success
nwb serve // Error
```

**Comment by maslianok** [comment]
The same error for 
node@5.8.0
npm@3.7.3

**Comment by insin** [comment]
Closing for now - please reopen if this is still an issue with newer versions (could it be related to the `sudo`? Thought it was ideal to avoid using it for global npm stuff)
